### PR TITLE
fix for copy google services script

### PR DESCRIPTION
**Pull request by vlavrynovych**
Related issues in similar projects:
- [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase/pull/391)
- [ionic-package-hooks](https://github.com/ionic-team/ionic-package-hooks/issues/30)

### CODE REVIEW

**Comment by BM9MobileBrasil** [comment]
This is much important!

**Comment by stetro** [comment]
Thanks for this fix! It's also important for me! 
But is there an explanation for `/Resources/Resources/...` ? Looks like a path bug to me?

**Comment by vlavrynovych** [comment]
Hi @stetro,

I do not remember exactly, but as I know for some cases (some plugins) we should put files here.
It's a common solution for most of the plugins with similar need and it's all configurable and as you see you can remove this destination if you want.

**Comment by vlavrynovych** [comment]
Accidentally closed. Sorry for that. Buttons are too close

**Comment by dleric** [comment]
This script also works for me. It should be included in the master.

**Comment by jaskaye17** [comment]
Is there any updates on merging this?

Also @vlavrynovych why do you if/else the following section? In my project I have both platforms installed. As a result my android directory never gets built. Shouldn't this be 2 if statements to build each one if it exists?

```
    if (directoryExists(IOS_DIR)) {
        copyKey(PLATFORM.IOS);
    } else if (directoryExists(ANDROID_DIR)) {
        copyKey(PLATFORM.ANDROID, updateStringsXml)		
    }
```

**Comment by vlavrynovych** [comment]
@jaskaye17 You are absolutely right! Sorry for that. Did you tried my fix? Except this finding did you faced any problems?

**Comment by jaskaye17** [comment]
@vlavrynovych Other than that the fix seems to be working for me locally. 

My next challenge is that I am using Ionic Pro Package. Their package service installs my plugins fresh each time and in doing so pulls the cordova-plugin-fcm master for each build which means I get the broken config and not your fix. Until this is merged I will not be able to test on their platform

**Comment by vlavrynovych** [comment]
@jaskaye17 I've just updated this PR by fix which has two `if` statements.
Thank you.

**Comment by jwelmac** [comment]
Thanks for this.
I realized that this was a major issue with a recent project when building the iOS package for submission.

I do hope @fechanique accepts this pull request soon so it will be in the main repository.

I have noted though that some CI servers throw errors when installing cordova plugins from a git url.

So for those who don't wish to change their dependencies and want to ensure the `GoogleService-Info.plist` gets copied to the `Resources/Resources` folder under `platforms/ios/[app name]` include the following in your `config.xml`
```
<platform name="ios">
  ...
  <resource-file src="GoogleService-Info.plist" target="Resources/GoogleService-Info.plist" />
</platform>
```

**Pull request merged**
