### PR TITLE
Hotfix Google-Services Build Version error

### PR DESCRIPTION
**Pull request by lp1bp**
Fixes Incompatibility with the last google-services version

### CODE REVIEW

**Comment by lp1bp** [comment]
Using the fix in the comments of https://github.com/fechanique/cordova-plugin-fcm/issues/306

**Comment by danielschiau** [comment]
any updates when this pr is going to get merged?

**Comment by pierrybos** [comment]
this changes fix my problems

**Comment by ruettenm** [comment]
please merge this 😉

**Comment by jperelli** [comment]
Please merge this! The issue is breaking the plugin completely!

**Comment by sajTempler** [comment]
works perfectly on Androids (Nexus 5x, LG g4, xperia z2, galaxy s6)

**Comment by fedecia** [comment]
please merge +1

**Comment by ucci** [comment]
please merge this request +++1

**Comment by fedecia** [comment]
Ended up switching to this plugin, works like a charm and 
has the a method to request notifications permission at any time with iOS https://www.npmjs.com/package/cordova-plugin-firebase. You're welcome

**Comment by jperelli** [comment]
I switched to cordova-plugin-firebase also. It seems to be more active.

**Pull request merged**
